from sqlalchemy.orm import Session
from backend.app.database.session import SessionLocal
from backend.app.database.models import (
    Passenger,
    Visa,
    WatchlistEntry,
    ScreeningRecordModel,
    SecurityAlertModel,
)

def seed_database():
    db: Session = SessionLocal()
    try:
        # Check if already seeded
        if db.query(Passenger).first():
            return

        # 1. Passengers (Synthetic Authorized Border Registry)
        passengers = [
            Passenger(
                id="PER-928101",
                name="Aditi Sharma",
                passport_number="Z8849102",
                national_id="XXXX-XXXX-9281",
                dob="1994-06-14",
                gender="F",
                nationality="Indian",
                address="Sector 4, Gandhinagar, Gujarat - 382004",
                status="ACTIVE",
                passport_issue_date="2020-01-10",
                passport_expiry_date="2030-01-09",
            ),
            Passenger(
                id="PER-849201",
                name="Alex Morgan",
                passport_number="P8742031",
                national_id="ID-US-4821",
                dob="1992-03-12",
                gender="M",
                nationality="United States",
                address="New York, United States",
                status="ACTIVE",
                passport_issue_date="2018-05-15",
                passport_expiry_date="2028-05-14",
            ),
            Passenger(
                id="PER-190482",
                name="Rohit Kumar",
                passport_number="Z1904821",
                national_id="XXXX-XXXX-1904",
                dob="1990-04-11",
                gender="M",
                nationality="Indian",
                address="Model Town, Panipat, Haryana",
                status="ACTIVE",
                passport_issue_date="2015-02-20",
                passport_expiry_date="2025-02-19",
            ),
            Passenger(
                id="PER-892184",
                name="Priya Patel",
                passport_number="Z8921849",
                national_id="XXXX-XXXX-8921",
                dob="1991-08-19",
                gender="F",
                nationality="Indian",
                address="Navrangpura, Ahmedabad, Gujarat",
                status="ACTIVE",
                passport_issue_date="2019-11-12",
                passport_expiry_date="2029-11-11",
            ),
            Passenger(
                id="PER-449201",
                name="Mohd. Farooq Tariq",
                passport_number="P4492019",
                national_id="XXXX-XXXX-4492",
                dob="1982-01-05",
                gender="M",
                nationality="Indian",
                address="Civil Lines, Moradabad, Uttar Pradesh",
                status="FLAGGED",
                passport_issue_date="2016-08-01",
                passport_expiry_date="2026-07-31",
            ),
            Passenger(
                id="PER-902811",
                name="Mohd. Tariq",
                passport_number="P9028114",
                national_id="XXXX-XXXX-9028",
                dob="1982-01-05",
                gender="M",
                nationality="Indian",
                address="Civil Lines, Moradabad, UP",
                status="FLAGGED",
                passport_issue_date="2017-03-10",
                passport_expiry_date="2027-03-09",
            ),
            Passenger(
                id="PER-042019",
                name="Vikramaditya Roy",
                passport_number="P0420191",
                national_id="DL-0420190038192",
                dob="1985-03-23",
                gender="M",
                nationality="Indian",
                address="Salt Lake City, Sector V, Kolkata, WB",
                status="ACTIVE",
                passport_issue_date="2021-04-14",
                passport_expiry_date="2031-04-13",
            ),
            Passenger(
                id="PER-492810",
                name="Sunita Devi Yadav",
                passport_number="P4928100",
                national_id="EPIC-BR-492810",
                dob="1979-12-10",
                gender="F",
                nationality="Indian",
                address="Village Siswa, Motihari, East Champaran, Bihar",
                status="ACTIVE",
                passport_issue_date="2018-09-22",
                passport_expiry_date="2028-09-21",
            ),
            Passenger(
                id="PER-883100",
                name="Arjun Singh",
                passport_number="BP-IN-NP-8831",
                national_id="NP-8831002",
                dob="1988-11-02",
                gender="M",
                nationality="Nepalese",
                address="Birgunj Border Sector, Ward 3, Parsa",
                status="ACTIVE",
                passport_issue_date="2022-01-15",
                passport_expiry_date="2027-01-14",
            ),
            Passenger(
                id="PER-892400",
                name="Amelia Stone",
                passport_number="P902184",
                national_id="UK-4829104",
                dob="1993-05-18",
                gender="F",
                nationality="British",
                address="London, UK",
                status="ACTIVE",
                passport_issue_date="2019-06-01",
                passport_expiry_date="2029-05-31",
            ),
            Passenger(
                id="PER-10001",
                name="Arun Sharma",
                passport_number="P10001",
                national_id="ID-IN-10001",
                dob="1999-04-12",
                gender="M",
                nationality="Indian",
                address="Connaught Place, New Delhi",
                status="ACTIVE",
                passport_issue_date="2021-01-01",
                passport_expiry_date="2031-01-01",
            ),
        ]
        db.add_all(passengers)
        db.commit()

        # 2. Visas
        visas = [
            Visa(
                visa_number="V10001",
                passport_number="P10001",
                name="Arun Sharma",
                visa_type="Tourist",
                entry_type="Multiple",
                valid_from="2024-01-01",
                valid_until="2027-01-01",
                stay_duration="90 Days",
                status="ACTIVE",
            ),
            Visa(
                visa_number="V-US-84920",
                passport_number="P8742031",
                name="Alex Morgan",
                visa_type="Business / Official Transit",
                entry_type="Multiple",
                valid_from="2023-01-01",
                valid_until="2028-01-01",
                stay_duration="180 Days",
                status="ACTIVE",
            ),
            Visa(
                visa_number="V-UK-90218",
                passport_number="P902184",
                name="Amelia Stone",
                visa_type="Tourist",
                entry_type="Multiple",
                valid_from="2023-05-01",
                valid_until="2026-05-01",
                stay_duration="90 Days",
                status="ACTIVE",
            ),
            Visa(
                visa_number="V-EXP-19048",
                passport_number="Z1904821",
                name="Rohit Kumar",
                visa_type="Transit Permit",
                entry_type="Single",
                valid_from="2022-01-01",
                valid_until="2023-01-01",  # EXPIRED
                stay_duration="30 Days",
                status="EXPIRED",
            ),
            Visa(
                visa_number="V-MISMATCH-99",
                passport_number="P0420191",  # belongs to Vikramaditya Roy, but issued with mismatch
                name="Priya Patel",
                visa_type="Tourist",
                entry_type="Single",
                valid_from="2024-01-01",
                valid_until="2026-01-01",
                stay_duration="30 Days",
                status="ACTIVE",
            ),
        ]
        db.add_all(visas)
        db.commit()

        # 3. Watchlist
        watchlist = [
            WatchlistEntry(
                id="WTL-904",
                name="Mohd. Tariq",
                passport_number="P9028114",
                national_id="XXXX-XXXX-9028",
                dob="1982-01-05",
                nationality="Indian",
                circular_ref="#LOC-2026-904",
                agency="IB / NIA / INTERPOL",
                severity="CRITICAL",
                description="Subject wanted under Central Agency Look Out Circular #LOC-2026-904. Initiate immediate checkpoint security protocol.",
            ),
            WatchlistEntry(
                id="WTL-905",
                name="Mohd. Farooq Tariq",
                passport_number="P4492019",
                national_id="XXXX-XXXX-4492",
                dob="1982-01-05",
                nationality="Indian",
                circular_ref="#LOC-2026-904",
                agency="IB & NIA Central Circular",
                severity="CRITICAL",
                description="Biometric facial query matched IB & NIA alert circular #LOC-2026-904. High risk subject.",
            ),
            WatchlistEntry(
                id="WTL-882",
                name="Unknown Subject",
                passport_number="FAKE-8821",
                national_id=None,
                dob="1980-01-01",
                nationality="Undetermined",
                circular_ref="#INTERPOL-RED-2025-88",
                agency="INTERPOL",
                severity="CRITICAL",
                description="Known forged document serial flagged across South Asian regional border security network.",
            ),
        ]
        db.add_all(watchlist)
        db.commit()

        # 4. Initial Screening Records
        records = [
            ScreeningRecordModel(
                id="VF-28491",
                name="Aditi Sharma",
                doc_type="Aadhaar Card",
                doc_number="XXXX-XXXX-9281",
                status="VERIFIED",
                timestamp="09:42 AM",
                checkpoint_id="CHK-00184",
                officer_id="SSB-OFC-8821",
                gender="F",
                dob="14-06-1994",
                address="Sector 4, Gandhinagar, Gujarat - 382004",
                nationality="Indian",
                match_score=99.2,
                ocr_confidence=99.8,
                security_checks={
                    "hologramDetected": True,
                    "tamperingDetected": False,
                    "watchlistMatch": False,
                    "biometricMatch": True,
                },
                notes="Standard citizen border transit. Identity verified against UIDAI ledger.",
            ),
            ScreeningRecordModel(
                id="VF-28490",
                name="Arjun Singh",
                doc_type="Border Pass",
                doc_number="BP-IN-NP-8831",
                status="NEEDS_REVIEW",
                timestamp="09:18 AM",
                checkpoint_id="CHK-00183",
                officer_id="SSB-OFC-8821",
                gender="M",
                dob="02-11-1988",
                address="Birgunj Border Sector, Ward 3, Parsa",
                nationality="Nepalese",
                match_score=84.1,
                ocr_confidence=91.0,
                security_checks={
                    "hologramDetected": True,
                    "tamperingDetected": False,
                    "watchlistMatch": False,
                    "biometricMatch": False,
                },
                notes="Secondary biometric mismatch on facial aging index. Requires manual officer interview.",
            ),
            ScreeningRecordModel(
                id="VF-28489",
                name="Priya Patel",
                doc_type="Passport",
                doc_number="Z8921849",
                status="MISMATCH",
                timestamp="08:56 AM",
                checkpoint_id="CHK-00182",
                officer_id="SSB-OFC-8821",
                gender="F",
                dob="19-08-1991",
                address="Navrangpura, Ahmedabad, Gujarat",
                nationality="Indian",
                match_score=42.6,
                ocr_confidence=78.4,
                security_checks={
                    "hologramDetected": False,
                    "tamperingDetected": True,
                    "watchlistMatch": False,
                    "biometricMatch": False,
                },
                notes="Security thread anomalies detected under UV wavelength check. Machine readable zone (MRZ) checksum failed.",
            ),
            ScreeningRecordModel(
                id="VF-28488",
                name="Mohd. Farooq Tariq",
                doc_type="Passport",
                doc_number="P4492019",
                status="HIGH_RISK",
                timestamp="08:12 AM",
                checkpoint_id="CHK-00184",
                officer_id="SSB-OFC-8821",
                gender="M",
                dob="05-01-1982",
                address="Civil Lines, Moradabad, Uttar Pradesh",
                nationality="Indian",
                match_score=31.0,
                ocr_confidence=96.5,
                security_checks={
                    "hologramDetected": False,
                    "tamperingDetected": True,
                    "watchlistMatch": True,
                    "biometricMatch": False,
                },
                notes="CRITICAL ALERT: Biometric facial query matched IB & NIA central alert circular #LOC-2026-904. Subject detained at Holding Bay 2.",
            ),
            ScreeningRecordModel(
                id="VF-28487",
                name="Vikramaditya Roy",
                doc_type="Driving License",
                doc_number="DL-0420190038192",
                status="VERIFIED",
                timestamp="07:45 AM",
                checkpoint_id="CHK-00184",
                officer_id="SSB-OFC-8821",
                gender="M",
                dob="23-03-1985",
                address="Salt Lake City, Sector V, Kolkata, WB",
                nationality="Indian",
                match_score=97.8,
                ocr_confidence=98.2,
                security_checks={
                    "hologramDetected": True,
                    "tamperingDetected": False,
                    "watchlistMatch": False,
                    "biometricMatch": True,
                },
                notes="Commercial transit vehicle operator clearance.",
            ),
            ScreeningRecordModel(
                id="VF-28486",
                name="Sunita Devi Yadav",
                doc_type="Voter ID",
                doc_number="EPIC-BR-492810",
                status="VERIFIED",
                timestamp="07:20 AM",
                checkpoint_id="CHK-00181",
                officer_id="SSB-OFC-8821",
                gender="F",
                dob="10-12-1979",
                address="Village Siswa, Motihari, East Champaran, Bihar",
                nationality="Indian",
                match_score=95.4,
                ocr_confidence=94.0,
                security_checks={
                    "hologramDetected": True,
                    "tamperingDetected": False,
                    "watchlistMatch": False,
                    "biometricMatch": True,
                },
                notes="Daily local border trade permit verified.",
            ),
        ]
        db.add_all(records)
        db.commit()

        # 5. Security Alerts
        alerts = [
            SecurityAlertModel(
                id="ALT-904",
                title="CRITICAL: Look Out Circular Hit at Sector 4",
                description="Biometric AI matched watchlist alert for suspect transit via Raxaul checkpoint.",
                severity="CRITICAL",
                timestamp="12 min ago",
                location="Checkpoint CHK-00184",
                acknowledged=False,
                doc_ref="VF-28488",
            ),
            SecurityAlertModel(
                id="ALT-903",
                title="Tampered Passport Batch Detected",
                description="Multiple passports with fraudulent laminated stamps reported at Indo-Nepal transit zone.",
                severity="WARNING",
                timestamp="1 hour ago",
                location="Sonauli Sector",
                acknowledged=True,
            ),
            SecurityAlertModel(
                id="ALT-902",
                title="Optical Scanner Firmware Updated",
                description="Spectral UV & IR neural model v4.2 calibrated for real-time hologram verification.",
                severity="INFO",
                timestamp="3 hours ago",
                location="HQ Central Command",
                acknowledged=True,
            ),
            SecurityAlertModel(
                id="ALT-901",
                title="High Transit Volume Warning",
                description="Vehicle & pedestrian queue exceeding standard threshold at Raxaul North Gate.",
                severity="WARNING",
                timestamp="5 hours ago",
                location="Checkpoint CHK-00184",
                acknowledged=True,
            ),
        ]
        db.add_all(alerts)
        db.commit()
    finally:
        db.close()
